### PR TITLE
New pinax-starter app requirements

### PR DESCRIPTION
**Pull request by arthur-wsw**
Add AppConfig
New tox config (drop 1.7 support)

### CODE REVIEW

**Comment by arthur-wsw** [comment]
I had to delete old migrations and regenerate new one with makemigration.py to make build succeed because of new AppConfig

**Comment by paltman** [comment]
We need to consider the upgrade path and at least document it in the change log.  Changing the app label from the default will mean the table will need to be renamed.  Instead of replacing the migrations, i'd  prefer to see a 4th one get added that ran a python migration step that copied over the old data if the old `eventlog_*` tables existed.  There [is an example of this](https://github.com/pinax/pinax-stripe/blob/bcbb7000ed390212062e0a6d02edb4aeae4c595a/pinax/stripe/migrations/0002_auto_20151205_1451.py) in `pinax-stripe`.

**Comment by jtauber** [comment]
Too late for this in 16.07 but did we want to consider it for a later release?

**Comment by grahamu** [comment]
Most concerns here are addressed in the latest PyPi release https://pypi.python.org/pypi/pinax-eventlog.

**Pull request closed without merging**
