### PR TITLE
Updated models.py to support MYSQL JSON Field

### PR DESCRIPTION
**Pull request by patrickscottbest**
Need eventlog to work with MySQL.

### CODE REVIEW

**Comment by KatherineMichel** [comment]
@patrickscottbest Awesome, thank you!

**Comment by blag** [comment]
This PR changed `models.py`, but didn't update the database migrations: #32.

**Comment by KatherineMichel** [comment]
@patrickscottbest Is this something you might be able to submit a PR to fix?

**Comment by patrickscottbest** [comment]
Hi yes I will take a look, but if memory serves we’ve got a fundamental problem with the existing migrations, I think I had to wipe some of them ... researching

**Comment by patrickscottbest** [comment]
I've commented on this in the bug, we seem to have a code divergence problem since migration `0003_auto_20160111_0208.py`

**Pull request merged**
